version: '3.8'
services:
  
  server:
    image: fortune_gem_server
    build: ./server/
    deploy:
      replicas: 3
    ports:
    - published: 2020
      target: 2020

  yinyang_api:
    image: yinyang_api 
    build: ./yinyang_api/    
    deploy:
      replicas: 3

  nginx:
    image: nginx:alpine 
    ports:
    - published: 80
      target: 80

