- name: Install Docker Dependencies
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3
    - python3-pip
    - python-setuptools
    - gnupg
    - lsb-release
    state: latest
    update_cache: true
- name: Add Docker GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Packages to Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }}
  tags: docker
    state: present
- name: Install Docker Engine
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - docker-compose
    - containerd.io
    - gnupg
    - lsb-release
    update_cache: true
- name: Start Docker service
  service: 
    name: docker
    state: started
- name: pip docker
  pip: 
    executable: pip3 
    name: docker